Repository LajnaLegenden/project-foodie, pull requests merged in 2023-02, with the labels that each got.

#5 Cbg 63 Timeline component
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/Timeline.razor
Labels: enhancement

#7 Cbg 63 Menu View Component
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/ViewStart.razor
  src/Pages/view-menu/compoents/MenuContainer.razor
  src/Shared/MainLayout.razor
Labels: enhancement

#10 Cbg 63 CSS
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/ViewMenu.razor.css
  src/Pages/view-menu/ViewStart.razor
  src/Pages/view-menu/ViewStart.razor.css
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/Dishes.razor.css
  src/Pages/view-menu/components/MenuContainer.razor
  src/Pages/view-menu/components/MenuContainer.razor.css
  src/Pages/view-menu/components/Timeline.razor
  src/Pages/view-menu/components/Timeline.razor.css
Labels: enhancement

#11 Cbg 63 css
  src/Pages/view-menu/ViewMenu.razor.css
  src/Pages/view-menu/ViewStart.razor.css
  src/Pages/view-menu/components/Dishes.razor.css
  src/Pages/view-menu/components/MenuContainer.razor.css
  src/wwwroot/css/site.css
Labels: enhancement

#14 Changing class based on order status of day
  src/Pages/view-menu/components/Timeline.razor
  src/Pages/view-menu/components/TimelineDay.razor
Labels: enhancement

#16 Cbg 63 css
  src/Pages/Index.razor
  src/Pages/_Host.cshtml
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/ViewMenu.razor.css
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/Dishes.razor.css
  src/Pages/view-menu/components/MenuContainer.razor
  src/Pages/view-menu/components/MenuContainer.razor.css
  src/Shared/MainLayout.razor
  src/Shared/MainLayout.razor.css
  src/Shared/NavHeader.razor
  src/Shared/NavHeader.razor.css
  src/Shared/SurveyPrompt.razor
  src/wwwroot/css/site.css
Labels: enhancement

#18 Cbg 63 category
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/ViewMenu.razor.css
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/Dishes.razor.css
  src/Pages/view-menu/components/MenuContainer.razor
  src/Pages/view-menu/components/Overview.razor
Labels: enhancement

#29 Cbg 63 view menu
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/MenuContainer.razor
  src/Pages/view-menu/components/MenuContainer.razor.css
  src/Pages/view-menu/components/Overview.razor
Labels: enhancement

#27 Cbg 63 allergen view component
  src/Pages/view-menu/components/Contents.razor
  src/Pages/view-menu/components/Contents.razor.css
  src/Pages/view-menu/components/Dishes.razor
Labels: enhancement

#30 Store all dishes in local storage
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/ViewMenu.razor.css
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/MenuContainer.razor
Labels: enhancement

#32 Cbg 63 css
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/ViewMenu.razor.css
  src/Pages/view-menu/ViewStart.razor
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/Dishes.razor.css
  src/Pages/view-menu/components/MenuContainer.razor
  src/Pages/view-menu/components/MenuContainer.razor.css
  src/Shared/NavHeader.razor
Labels: enhancement

#36 Cbg 63 css
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/ViewMenu.razor.css
  src/Pages/view-menu/ViewStart.razor
  src/Pages/view-menu/ViewStart.razor.css
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/MenuContainer.razor.css
  src/Pages/view-menu/components/Overview.razor
  src/Pages/view-menu/components/Overview.razor.css
  src/Shared/MainLayout.razor.css
  src/Shared/NavHeader.razor.css
  src/wwwroot/css/site.css
Labels: enhancement

#37 Cbg 63 css
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/components/Overview.razor
  src/Pages/view-menu/components/Overview.razor.css
Labels: enhancement

#38 Cbg 63 timeline
  src/Pages/_Host.cshtml
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/MenuContainer.razor
  src/Pages/view-menu/components/Overview.razor.css
  src/Pages/view-menu/components/TimeLineSection.razor
  src/Pages/view-menu/components/TimeLineSection.razor.css
  src/Pages/view-menu/components/Timeline.razor
  src/Pages/view-menu/components/Timeline.razor.css
  src/Program.cs
  src/Services/BrowerService.cs
Labels: enhancement

#39 Cbg 63 css
  src/Pages/_Host.cshtml
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/components/TimeLineSection.razor.css
Labels: enhancement

#40 Cbg 64 no food checkbox
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/Dishes.razor.css
  src/Pages/view-menu/components/MenuContainer.razor
  src/Pages/view-menu/components/MenuContainer.razor.css
Labels: enhancement

#42 Cbg 64 adapt label to meal type
  src/Pages/view-menu/components/MenuContainer.razor
Labels: enhancement

#44 category buttons work on all days, and dishes sorted by category
  src/Model/Category.cs
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/ViewMenu.razor.css
  src/Pages/view-menu/components/MenuContainer.razor
  src/Pages/view-menu/components/MenuContainer.razor.css
Labels: enhancement

#45 CBG-63 Added get allergens and ingredients from local database
  src/Pages/view-menu/components/Dishes.razor
  src/Repository/DishRepository.cs
Labels: enhancement

#46 Bugfixes for category and overview
  src/Pages/view-menu/ViewMenu.razor
Labels: bugfix

#48 Cbg 63 64 fixes
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/components/Overview.razor
Labels: enhancement

#56 Bugfix Scroll on pc
  src/Pages/view-menu/ViewMenu.razor
Labels: bugfix

#57 Bugfix with empty localstorage
  src/Pages/view-menu/components/Overview.razor
Labels: bugfix

#58 CBG-346 Fixed reset dishes quantity to 0 when checkbox checked
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/MenuContainer.razor
Labels: bugfix

#59 CBG-321 jump between days
  src/Modules/DayMenuHelper.cs
  src/Modules/UrlHelpers.cs
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/components/Overview.razor
  src/Pages/view-menu/components/Overview.razor.css
  src/Pages/view-menu/components/TimeLineSection.razor
  src/Pages/view-menu/components/Timeline.razor
  src/Pages/view-menu/components/TimelineDay.razor
  src/project-foodie.csproj
Labels: enhancement

#60 Cbg 65 order confirmed view
  src/Model/DatabaseContext.cs
  src/Modules/localstorage.cs
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/components/Confirmed.razor
  src/Pages/view-menu/components/Overview.razor
Labels: enhancement

#66 Cbg 355 Menu fit in full page
  src/Pages/view-menu/ViewMenu.razor.css
  src/Pages/view-menu/components/MenuContainer.razor.css
  src/Pages/view-menu/components/TimeLineSection.razor
  src/Pages/view-menu/components/TimeLineSection.razor.css
  src/Pages/view-menu/components/Timeline.razor
  src/Shared/NavHeader.razor.css
Labels: enhancement, bugfix

#67 CBG-327 css auto prefixer
  .gitignore
  Dockerfile
  src/package-lock.json
  src/package.json
  src/postcss.config.js
  src/project-foodie.csproj
Labels: devops

#68 CBG-327 css auto prefixer
  src/postcss.config.js
Labels: devops

#71 Cbg 60 design order confirmed view
  src/Modules/localstorage.cs
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/ViewStart.razor.css
  src/Pages/view-menu/components/Confirmed.razor
  src/Pages/view-menu/components/Confirmed.razor.css
  src/Pages/view-menu/components/MenuContainer.razor
  src/Shared/MainLayout.razor
  src/Shared/MainLayout.razor.css
  src/Shared/NavHeader.razor.css
  src/wwwroot/images/confetti.png
  src/wwwroot/images/confetti.png:Zone.Identifier
Labels: enhancement, bugfix

#74 Cbg 60 design order confirmed view
  src/Pages/_Host.cshtml
  src/Pages/view-menu/components/Confirmed.razor
  src/Pages/view-menu/components/Confirmed.razor.css
Labels: enhancement

#78 Fixed back choose btn
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/Dishes.razor.css
Labels: enhancement

#80 Cbg 73 Order details
  src/Modules/DayMenuHelper.cs
  src/Pages/my-page/MyPage.razor
  src/Pages/my-page/components/OrderTable.razor
  src/Pages/my-page/components/OrderTable.razor.css
  src/Pages/webmaster/components/Db.razor
Labels: enhancement, bugfix
