Repository LajnaLegenden/project-foodie, pull requests merged in 2023-03, with the labels that each got.

#82 Cbg 369 redesign Shoopint cart to fit foodie website
  src/Pages/view-menu/components/Dishes.razor.css
  src/Shared/NavHeader.razor
  src/Shared/NavHeader.razor.css
  src/wwwroot/images/shopping-basket.svg
Labels: enhancement

#83 Cbg 369 redesign Infobox and choose btn
  src/Pages/view-menu/components/Dishes.razor
  src/Pages/view-menu/components/Dishes.razor.css
  src/wwwroot/images/info-circle.svg
  src/wwwroot/images/info-circle1.svg
Labels: enhancement

#89 Dispose of HandleLocationChanged
  .github/workflows/format.yml
  src/Pages/my-page/OrderHistory.razor
  src/Pages/view-menu/ViewMenu.razor
  src/Pages/view-menu/components/Dishes.razor
  src/Shared/NavHeader.razor.css
Labels: enhancement, bugfix

#91 Fix error order details
  src/Repository/OrderRepository.cs
Labels: bugfix

#94 Cbg 399 design and implement sidebar me page
  src/Pages/my-page/MyPage.razor
  src/Pages/my-page/MyPage.razor.css
  src/Pages/my-page/OrderHistory.razor
  src/Pages/my-page/OrderHistory.razor.css
  src/Pages/my-page/components/Sidebar.razor
  src/Pages/my-page/components/Sidebar.razor.css
Labels: enhancement

#99 Cbg 72 design history view
  src/Pages/my-page/MyPageBase.razor
  src/Pages/my-page/MyPageBase.razor.css
  src/Pages/my-page/components/MyPage.razor
  src/Pages/my-page/components/OrderHistory/OrderHistory.razor
  src/Pages/my-page/components/OrderHistory/OrderHistory.razor.css
  src/Pages/my-page/components/OrderHistory/OrderTable.razor
  src/Pages/my-page/components/OrderHistory/OrderTable.razor.css
Labels: enhancement

#100 Sprint 4 bugfixes
  src/Pages/view-menu/ViewMenu.razor.css
  src/Pages/view-menu/ViewStart.razor
  src/Pages/view-menu/components/MenuContainer.razor.css
  src/Shared/MobileHeader.razor
  src/Shared/MobileHeader.razor.css
  src/Shared/NavHeader.razor
  src/Shared/NavHeader.razor.css
  src/wwwroot/css/site.css
Labels: bugfix

#101 Sprint 4 bugfixes and updates
  src/Pages/Index.razor
  src/Pages/Index.razor.css
  src/Pages/my-page/MyPageBase.razor.css
  src/Pages/my-page/components/MyPage.razor
  src/Pages/my-page/components/MyPage.razor.css
  src/Pages/my-page/components/OrderHistory/OrderHistory.razor
  src/Pages/my-page/components/OrderHistory/OrderHistory.razor.css
  src/Pages/view-menu/ViewStart.razor.css
  src/Shared/NavHeader.razor
  src/Shared/NavHeader.razor.css
  src/wwwroot/images/foodimg.png
Labels: enhancement, bugfix
